---

sudo: true
services:
  - docker

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: 2.7
      cache: pip

script:
  - mkdir -p test/
  - ln -sf . test/.ci
  - echo "CI_PYENV_PROJECT_NAME=my-special-project" > .ci-pyenv
  - echo "CI_PYENV_PROJECT_PYTHON=2.7.15" >> .ci-pyenv
  - cd test; .ci/init-pyenv
  - cd test; .ci/run-pyenv pip list
  - cd test; .ci/run-pyenv pyenv versions
