#!/bin/bash -e
# MIT License
#
# Copyright (c) 2018
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

##########################################################################
# Description: This is helper script for creating your virtualenv
#
# Variables:
#   Replace %%PROJECT_NAME%% - With the name of your project that you are working on Ex: "codylane.pyenv"
#   Replace %%PROJECT_PYTHON%% - With version of python you want to use in your virtualenv. Ex: "2.7.15"
#
# Usage:
#   This file is meant to be executed.
#   Ex:
#     chmod 755 .jenkins/init
#     .jenkins/init
#
# License: MIT
# Date: 2018-08-01
# Author: Cody Lane
##########################################################################


CMD="${BASH_SOURCE[0]}"
BIN_DIR="${CMD%/*}"
. "${BIN_DIR}/enable-pyenv"

eval "$@"
